package com.minimart.pos.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/** Renders a [BusinessReportData] as a multi-page A4 PDF and shares it (WhatsApp first). */
object BusinessReportPdf {

    private const val W = 595            // A4 at 72 dpi
    private const val H = 842
    private const val M = 40f
    private const val BOTTOM = H - 60f
    private val TEAL = Color.parseColor("#00897B")
    private val GREY = Color.parseColor("#607D8B")
    private val LIGHT = Color.parseColor("#ECEFF1")

    private fun money(cur: String, v: Double) = "$cur ${String.format(Locale.US, "%,.2f", v)}"

    private fun paint(size: Float, color: Int = Color.BLACK, bold: Boolean = false, align: Paint.Align = Paint.Align.LEFT) =
        Paint().apply {
            isAntiAlias = true; textSize = size; this.color = color; textAlign = align
            typeface = if (bold) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        }

    /** Tracks the current page/cursor and starts a new page when content would overflow. */
    private class Writer(val doc: PdfDocument, val data: BusinessReportData) {
        var pageNo = 0
        lateinit var page: PdfDocument.Page
        lateinit var canvas: Canvas
        var y = 0f

        fun newPage() {
            if (pageNo > 0) finishPage()
            pageNo++
            page = doc.startPage(PdfDocument.PageInfo.Builder(W, H, pageNo).create())
            canvas = page.canvas
            y = M
            if (pageNo > 1) {
                canvas.drawText("${data.storeName} — Business Report (${data.periodLabel})", M, y + 4, paint(10f, GREY))
                y += 24f
            }
        }

        fun ensure(height: Float) { if (y + height > BOTTOM) newPage() }

        fun finishPage() {
            canvas.drawText("Generated by MiniMart POS", M, H - 28f, paint(9f, GREY))
            canvas.drawText("Page $pageNo", W - M, H - 28f, paint(9f, GREY, align = Paint.Align.RIGHT))
            doc.finishPage(page)
        }
    }

    fun generate(context: Context, data: BusinessReportData): File {
        val dir = File(context.filesDir, "receipts").apply { mkdirs() }
        val stamp = SimpleDateFormat("yyyyMMdd_HHmm", Locale.US).format(Date(data.generatedAt))
        val file = File(dir, "business_report_$stamp.pdf")
        val doc = PdfDocument()
        try {
            val w = Writer(doc, data)
            w.newPage()
            drawHeader(w)
            drawKpis(w)
            drawSummary(w)
            drawPayments(w)
            drawTopSellers(w)
            drawExpenses(w)
            w.finishPage()
            FileOutputStream(file).use { doc.writeTo(it) }
        } finally {
            doc.close()
        }
        return file
    }

    private fun section(w: Writer, title: String) {
        w.ensure(70f)
        w.y += 14f
        w.canvas.drawText(title, M, w.y, paint(14f, TEAL, bold = true))
        w.y += 8f
        w.canvas.drawLine(M, w.y, W - M, w.y, Paint().apply { color = TEAL; strokeWidth = 1.2f })
        w.y += 6f
    }

    private fun row(w: Writer, left: String, right: String, bold: Boolean = false, color: Int = Color.BLACK, rightCenterText: String? = null) {
        w.ensure(22f)
        w.y += 16f
        w.canvas.drawText(left.take(48), M, w.y, paint(11.5f, color, bold))
        rightCenterText?.let { w.canvas.drawText(it, W - M - 150f, w.y, paint(11.5f, GREY, align = Paint.Align.RIGHT)) }
        w.canvas.drawText(right, W - M, w.y, paint(11.5f, color, bold, Paint.Align.RIGHT))
        w.y += 4f
    }

    private fun drawHeader(w: Writer) {
        val c = w.canvas
        c.drawRect(0f, 0f, W.toFloat(), 118f, Paint().apply { color = TEAL })
        c.drawText(w.data.storeName.uppercase(), M, 52f, paint(22f, Color.WHITE, bold = true))
        c.drawText("Business Report", M, 78f, paint(14f, Color.WHITE))
        c.drawText(w.data.periodLabel, M, 100f, paint(12f, Color.WHITE))
        val gen = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault()).format(Date(w.data.generatedAt))
        c.drawText("Generated $gen", W - M, 100f, paint(10f, Color.WHITE, align = Paint.Align.RIGHT))
        w.y = 118f + 16f
    }

    private fun drawKpis(w: Writer) {
        val d = w.data
        val boxW = (W - 2 * M - 20f) / 3f
        val items = listOf(
            "REVENUE" to money(d.currency, d.revenue),
            "SALES" to d.transactions.toString(),
            "AVG BASKET" to money(d.currency, d.averageBasket)
        )
        items.forEachIndexed { i, (label, value) ->
            val x = M + i * (boxW + 10f)
            w.canvas.drawRoundRect(x, w.y, x + boxW, w.y + 64f, 10f, 10f, Paint().apply { color = LIGHT })
            w.canvas.drawText(label, x + 12f, w.y + 22f, paint(9.5f, GREY, bold = true))
            w.canvas.drawText(value, x + 12f, w.y + 48f, paint(if (value.length > 14) 13f else 16f, Color.BLACK, bold = true))
        }
        w.y += 64f
    }

    private fun drawSummary(w: Writer) {
        val d = w.data
        section(w, "Summary")
        row(w, "Gross sales (completed)", money(d.currency, d.revenue))
        row(w, "Discounts given", money(d.currency, d.discounts))
        row(w, "VAT included in sales", money(d.currency, d.vatIncluded))
        row(w, "Refunded / voided (${d.reversedCount})", money(d.currency, d.reversedAmount), color = if (d.reversedCount > 0) Color.parseColor("#C62828") else Color.BLACK)
        row(w, "Expenses recorded", money(d.currency, d.totalExpenses))
        row(w, "Net (sales − expenses)", money(d.currency, d.net), bold = true,
            color = if (d.net >= 0) Color.parseColor("#2E7D32") else Color.parseColor("#C62828"))
    }

    private fun drawPayments(w: Writer) {
        val d = w.data
        section(w, "Sales by payment method")
        if (d.payments.isEmpty()) { row(w, "No completed sales in this period", ""); return }
        d.payments.forEach { p ->
            val pct = if (d.revenue > 0) p.amount / d.revenue * 100 else 0.0
            row(w, "${p.label}  (${p.count} sale${if (p.count == 1) "" else "s"})", money(d.currency, p.amount),
                rightCenterText = String.format(Locale.US, "%.1f%%", pct))
        }
    }

    private fun drawTopSellers(w: Writer) {
        val d = w.data
        section(w, "Top selling products")
        if (d.topSellers.isEmpty()) { row(w, "No product sales in this period", ""); return }
        d.topSellers.forEachIndexed { i, s ->
            row(w, "${i + 1}. ${s.name}", money(d.currency, s.revenue), rightCenterText = "${s.quantity} sold")
        }
    }

    private fun drawExpenses(w: Writer) {
        val d = w.data
        section(w, "Expenses by category")
        if (d.expenses.isEmpty()) { row(w, "No expenses recorded in this period", ""); return }
        d.expenses.forEach { e -> row(w, e.category, money(d.currency, e.amount)) }
        row(w, "Total expenses", money(d.currency, d.totalExpenses), bold = true)
    }

    // ── Sharing ───────────────────────────────────────────────────────────────

    fun getShareUri(context: Context, file: File): Uri =
        FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)

    /** Opens WhatsApp with the PDF attached; falls back to the system share sheet if WhatsApp isn't installed. */
    fun shareViaWhatsApp(context: Context, uri: Uri, data: BusinessReportData) {
        val text = "${data.storeName} — Business report (${data.periodLabel})\n" +
            "Revenue: ${money(data.currency, data.revenue)} • ${data.transactions} sales"
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, "${data.storeName} business report")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        val whatsapp = Intent(intent).setPackage("com.whatsapp")
        try {
            context.startActivity(whatsapp)
        } catch (_: Exception) {
            context.startActivity(Intent.createChooser(intent, "Share report").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
        }
    }
}
